package app

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"gxShell/backend/types"

	"golang.org/x/crypto/ssh/knownhosts"
)

func TestBackupPreviewDisclosesAIChangesWithoutCredentials(t *testing.T) {
	a := backupTestApp(t)
	settings, err := a.store.GetSettings()
	if err != nil {
		t.Fatal(err)
	}
	settings.Ai = types.AiConfig{Provider: "openai", Endpoint: "https://current.invalid/v1", Model: "current-model", APIKey: "legacy-test-key"}
	if err := a.store.SaveSettings(settings); err != nil {
		t.Fatal(err)
	}
	payload := backupTestPayload()
	payload.Settings.Ai = types.AiConfig{Provider: "custom", Endpoint: "https://imported.invalid/v1", Model: "imported-model"}
	plan, err := a.planBackup(payload, "[]", "keep", true)
	if err != nil {
		t.Fatal(err)
	}
	want := []backupSettingChange{
		{Field: "provider", Before: "openai", After: "custom"},
		{Field: "endpoint", Before: "https://current.invalid/v1", After: "https://imported.invalid/v1"},
		{Field: "model", Before: "current-model", After: "imported-model"},
	}
	if !reflect.DeepEqual(plan.preview.AIChanges, want) {
		t.Fatalf("AI changes: %#v", plan.preview.AIChanges)
	}
	encoded, _ := json.Marshal(plan.preview)
	if strings.Contains(string(encoded), settings.Ai.APIKey) || plan.settings.Ai.APIKey != "" {
		t.Fatal("preview exposed a credential")
	}
	if plan.settings.Ai.Endpoint != payload.Settings.Ai.Endpoint {
		t.Fatal("preview differs from imported settings")
	}
	unchanged := payload
	unchanged.Settings.Ai = settings.Ai
	for _, tc := range []struct {
		payload backupPayload
		restore bool
	}{{payload, false}, {unchanged, true}} {
		plan, err := a.planBackup(tc.payload, "[]", "keep", tc.restore)
		if err != nil {
			t.Fatal(err)
		}
		if len(plan.preview.AIChanges) != 0 {
			t.Fatal("preview reports unchanged AI configuration")
		}
	}
}

func TestBackupPreviewKeepsLocalLogRetentionPolicy(t *testing.T) {
	for _, enabled := range []bool{false, true} {
		a := backupTestApp(t)
		settings, err := a.store.GetSettings()
		if err != nil {
			t.Fatal(err)
		}
		settings.SessionLogRetention = types.SessionLogRetentionSettings{Enabled: enabled, MaxAgeDays: 60, MaxTotalMB: 4096}
		if err := a.store.SaveSettings(settings); err != nil {
			t.Fatal(err)
		}
		payload := backupTestPayload()
		payload.Settings.SessionLogRetention = types.SessionLogRetentionSettings{Enabled: !enabled, MaxAgeDays: 1, MaxTotalMB: 1}
		plan, err := a.planBackup(payload, "[]", "keep", true)
		if err != nil {
			t.Fatal(err)
		}
		if plan.settings.SessionLogRetention != settings.SessionLogRetention {
			t.Fatal("backup replaced local log deletion policy")
		}
	}
}

func TestBackupPreviewRejectsOversizedMergedKnownHosts(t *testing.T) {
	a := backupTestApp(t)
	const maximum = 10 * 1024 * 1024
	const comment = "# retained comment\n"
	existing := strings.Repeat(comment, maximum/len(comment))
	filename := filepath.Join(a.store.DataDir(), "known_hosts")
	if err := os.WriteFile(filename, []byte(existing), 0600); err != nil {
		t.Fatal(err)
	}
	payload := backupTestPayload()
	key, _ := backupTestKey(t)
	payload.KnownHosts = knownhosts.Line([]string{"imported.invalid"}, key) + "\n"
	plan, err := a.planBackup(payload, "[]", "keep", false)
	if err == nil || plan != nil || !strings.Contains(err.Error(), "known_hosts exceeds 10 MiB") {
		t.Fatalf("oversized merge was not rejected at preview: %v", err)
	}
	data, err := os.ReadFile(filename)
	if err != nil || string(data) != existing {
		t.Fatal("preview changed known_hosts")
	}
}

func TestBackupDecryptsLegacyKDFAndBoundsIterationCost(t *testing.T) {
	// Generated by the original 210000-round exporter; keep this fixture when
	// the cost of new exports changes again.
	const legacy = `{"format":"gxShell-backup-v1","kdf":"PBKDF2-HMAC-SHA256","iterations":210000,"salt":"SClqaYx2FKnY2fgKri6geA","nonce":"bslg4t5fR5Zphk3Z","ciphertext":"I0w4CD98G2i2G5GRpzjACuKH8iDl89npxjK+W1YzAxUy16qcyp4/V3s2kH6dZt/tZYBzJFWbA2s6icxErFp79ps"}`
	var envelope backupEnvelope
	if err := json.Unmarshal([]byte(legacy), &envelope); err != nil {
		t.Fatal(err)
	}
	plain, err := decryptBackup(envelope, "legacy fixture passphrase")
	if err != nil || string(plain) != `{"format":"gxShell-backup-v1","fixture":"legacy"}` {
		t.Fatalf("legacy backup: %s %v", plain, err)
	}
	current, err := encryptBackup(plain, "legacy fixture passphrase")
	if err != nil || current.Iterations != 600000 {
		t.Fatalf("new export cost: %d %v", current.Iterations, err)
	}
	for _, iterations := range []int{-1, 0, 210001, 600001, 1 << 30} {
		envelope.Iterations = iterations
		if _, err := decryptBackup(envelope, "legacy fixture passphrase"); err == nil {
			t.Fatalf("accepted unsupported cost %d", iterations)
		}
	}
}

func TestBackupCommandConflictIndexIncludesImportedCopies(t *testing.T) {
	for _, policy := range []string{"keep", "copy"} {
		t.Run(policy, func(t *testing.T) {
			a := backupTestApp(t)
			if err := a.store.SaveCommands([]types.CommandTemplate{{ID: "existing", Name: "Status", Category: "Ops", Command: "uptime"}}); err != nil {
				t.Fatal(err)
			}
			payload := backupTestPayload()
			payload.Commands = []types.CommandTemplate{
				{ID: "one", Name: "Status", Category: "Ops", Command: "uptime"},
				{ID: "two", Name: "Status (imported)", Category: "Ops", Command: "uptime"},
				{ID: "existing", Name: "Other", Category: "Ops", Command: "uptime"},
			}
			plan, err := a.planBackup(payload, "[]", policy, false)
			if err != nil {
				t.Fatal(err)
			}
			var commands []types.CommandTemplate
			if err := json.Unmarshal(plan.after["commands.json"], &commands); err != nil {
				t.Fatal(err)
			}
			if policy == "copy" {
				if len(commands) != 4 || commands[1].Name != "Status (imported)" || commands[2].Name != "Status (imported) (imported)" || commands[3].Name != "Other (imported)" {
					t.Fatalf("copy conflicts: %#v", commands)
				}
			} else if len(commands) != 2 || commands[1].Name != "Status (imported)" || plan.preview.Skipped != 2 {
				t.Fatalf("keep conflicts: %#v", commands)
			}
		})
	}
}
