// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFirewallRule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['AddFirewallRule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddTunnelRule(arg1, arg2) {
  return window['go']['app']['App']['AddTunnelRule'](arg1, arg2);
}

export function AiChat(arg1) {
  return window['go']['app']['App']['AiChat'](arg1);
}

export function AiContinueChat(arg1) {
  return window['go']['app']['App']['AiContinueChat'](arg1);
}

export function AiExecuteTool(arg1, arg2) {
  return window['go']['app']['App']['AiExecuteTool'](arg1, arg2);
}

export function AiExecuteTools(arg1, arg2) {
  return window['go']['app']['App']['AiExecuteTools'](arg1, arg2);
}

export function AnswerKeyboardInteractive(arg1, arg2, arg3) {
  return window['go']['app']['App']['AnswerKeyboardInteractive'](arg1, arg2, arg3);
}

export function CancelAiChat(arg1, arg2) {
  return window['go']['app']['App']['CancelAiChat'](arg1, arg2);
}

export function CancelTransfer(arg1) {
  return window['go']['app']['App']['CancelTransfer'](arg1);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['app']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectLocal(arg1, arg2) {
  return window['go']['app']['App']['ConnectLocal'](arg1, arg2);
}

export function ConnectQuick(arg1, arg2, arg3) {
  return window['go']['app']['App']['ConnectQuick'](arg1, arg2, arg3);
}

export function ConnectWithSecrets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ConnectWithSecrets'](arg1, arg2, arg3, arg4, arg5);
}

export function ContainerLogs(arg1, arg2, arg3) {
  return window['go']['app']['App']['ContainerLogs'](arg1, arg2, arg3);
}

export function CreateCommand(arg1) {
  return window['go']['app']['App']['CreateCommand'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['app']['App']['CreateProfile'](arg1);
}

export function CreateRemoteDir(arg1, arg2) {
  return window['go']['app']['App']['CreateRemoteDir'](arg1, arg2);
}

export function DeleteCommand(arg1) {
  return window['go']['app']['App']['DeleteCommand'](arg1);
}

export function DeleteCronJob(arg1, arg2) {
  return window['go']['app']['App']['DeleteCronJob'](arg1, arg2);
}

export function DeleteFirewallRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteFirewallRule'](arg1, arg2, arg3, arg4);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeleteRecording(arg1) {
  return window['go']['app']['App']['DeleteRecording'](arg1);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['app']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DeleteWebsite(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteWebsite'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadFileWithPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DownloadFileWithPolicy'](arg1, arg2, arg3, arg4);
}

export function DownloadFolder(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadFolder'](arg1, arg2, arg3);
}

export function DuplicateProfile(arg1) {
  return window['go']['app']['App']['DuplicateProfile'](arg1);
}

export function ExportHistory() {
  return window['go']['app']['App']['ExportHistory']();
}

export function ExportProfiles(arg1) {
  return window['go']['app']['App']['ExportProfiles'](arg1);
}

export function GetAiConfig() {
  return window['go']['app']['App']['GetAiConfig']();
}

export function GetAiUsage() {
  return window['go']['app']['App']['GetAiUsage']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetFirewallStatus(arg1) {
  return window['go']['app']['App']['GetFirewallStatus'](arg1);
}

export function GetLatestMetrics(arg1) {
  return window['go']['app']['App']['GetLatestMetrics'](arg1);
}

export function GetNetworkPath(arg1) {
  return window['go']['app']['App']['GetNetworkPath'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['app']['App']['GetProfile'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStartupFile() {
  return window['go']['app']['App']['GetStartupFile']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function GetWebsiteConfig(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetWebsiteConfig'](arg1, arg2, arg3, arg4);
}

export function GetWebsiteStatus(arg1) {
  return window['go']['app']['App']['GetWebsiteStatus'](arg1);
}

export function ImportOpenSSHConfig() {
  return window['go']['app']['App']['ImportOpenSSHConfig']();
}

export function ImportProfiles() {
  return window['go']['app']['App']['ImportProfiles']();
}

export function IsMarkdownContextMenuRegistered() {
  return window['go']['app']['App']['IsMarkdownContextMenuRegistered']();
}

export function IsRecording(arg1) {
  return window['go']['app']['App']['IsRecording'](arg1);
}

export function IsTextContextMenuRegistered() {
  return window['go']['app']['App']['IsTextContextMenuRegistered']();
}

export function ListAiModels(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListAiModels'](arg1, arg2, arg3);
}

export function ListCommands() {
  return window['go']['app']['App']['ListCommands']();
}

export function ListContainers(arg1, arg2) {
  return window['go']['app']['App']['ListContainers'](arg1, arg2);
}

export function ListCronJobs(arg1) {
  return window['go']['app']['App']['ListCronJobs'](arg1);
}

export function ListKnownHosts() {
  return window['go']['app']['App']['ListKnownHosts']();
}

export function ListLocalDir(arg1) {
  return window['go']['app']['App']['ListLocalDir'](arg1);
}

export function ListLogFiles() {
  return window['go']['app']['App']['ListLogFiles']();
}

export function ListMarkdownFilesInDir(arg1) {
  return window['go']['app']['App']['ListMarkdownFilesInDir'](arg1);
}

export function ListProfiles() {
  return window['go']['app']['App']['ListProfiles']();
}

export function ListRecordings() {
  return window['go']['app']['App']['ListRecordings']();
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['app']['App']['ListRemoteDir'](arg1, arg2);
}

export function ListRemoteMarkdownFilesInDir(arg1, arg2) {
  return window['go']['app']['App']['ListRemoteMarkdownFilesInDir'](arg1, arg2);
}

export function ListRemoteTextFilesInDir(arg1, arg2) {
  return window['go']['app']['App']['ListRemoteTextFilesInDir'](arg1, arg2);
}

export function ListServices(arg1) {
  return window['go']['app']['App']['ListServices'](arg1);
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function ListTextFilesInDir(arg1) {
  return window['go']['app']['App']['ListTextFilesInDir'](arg1);
}

export function ListTunnelStatus(arg1) {
  return window['go']['app']['App']['ListTunnelStatus'](arg1);
}

export function LocalHomeDir() {
  return window['go']['app']['App']['LocalHomeDir']();
}

export function LogCommand(arg1, arg2) {
  return window['go']['app']['App']['LogCommand'](arg1, arg2);
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function OpenRecentMarkdownFile(arg1) {
  return window['go']['app']['App']['OpenRecentMarkdownFile'](arg1);
}

export function OpenRecentTextFile(arg1) {
  return window['go']['app']['App']['OpenRecentTextFile'](arg1);
}

export function OpenRecordingsDir() {
  return window['go']['app']['App']['OpenRecordingsDir']();
}

export function PingHost(arg1, arg2) {
  return window['go']['app']['App']['PingHost'](arg1, arg2);
}

export function ReadLocalFile(arg1) {
  return window['go']['app']['App']['ReadLocalFile'](arg1);
}

export function ReadLocalMarkdownResourceDataURL(arg1, arg2) {
  return window['go']['app']['App']['ReadLocalMarkdownResourceDataURL'](arg1, arg2);
}

export function ReadLocalPDFBase64(arg1) {
  return window['go']['app']['App']['ReadLocalPDFBase64'](arg1);
}

export function ReadLogFile(arg1) {
  return window['go']['app']['App']['ReadLogFile'](arg1);
}

export function ReadLogs(arg1) {
  return window['go']['app']['App']['ReadLogs'](arg1);
}

export function ReadRecording(arg1) {
  return window['go']['app']['App']['ReadRecording'](arg1);
}

export function ReadRemoteMarkdownFile(arg1, arg2) {
  return window['go']['app']['App']['ReadRemoteMarkdownFile'](arg1, arg2);
}

export function ReadRemoteMarkdownResourceDataURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadRemoteMarkdownResourceDataURL'](arg1, arg2, arg3);
}

export function ReadRemoteTextFile(arg1, arg2) {
  return window['go']['app']['App']['ReadRemoteTextFile'](arg1, arg2);
}

export function Reconnect(arg1) {
  return window['go']['app']['App']['Reconnect'](arg1);
}

export function ReconnectWithSecrets(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReconnectWithSecrets'](arg1, arg2, arg3);
}

export function RegisterMarkdownContextMenu() {
  return window['go']['app']['App']['RegisterMarkdownContextMenu']();
}

export function RegisterTextContextMenu() {
  return window['go']['app']['App']['RegisterTextContextMenu']();
}

export function RemoveContainer(arg1, arg2, arg3) {
  return window['go']['app']['App']['RemoveContainer'](arg1, arg2, arg3);
}

export function RemoveKnownHost(arg1, arg2) {
  return window['go']['app']['App']['RemoveKnownHost'](arg1, arg2);
}

export function RemoveTunnelRule(arg1, arg2) {
  return window['go']['app']['App']['RemoveTunnelRule'](arg1, arg2);
}

export function RenameRemoteFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameRemoteFile'](arg1, arg2, arg3);
}

export function ResetAiUsage() {
  return window['go']['app']['App']['ResetAiUsage']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveLocalMarkdownLink(arg1, arg2) {
  return window['go']['app']['App']['ResolveLocalMarkdownLink'](arg1, arg2);
}

export function ResolveRemoteMarkdownLink(arg1, arg2) {
  return window['go']['app']['App']['ResolveRemoteMarkdownLink'](arg1, arg2);
}

export function RestartContainer(arg1, arg2) {
  return window['go']['app']['App']['RestartContainer'](arg1, arg2);
}

export function RestartTunnels(arg1) {
  return window['go']['app']['App']['RestartTunnels'](arg1);
}

export function RestoreTextFiles(arg1) {
  return window['go']['app']['App']['RestoreTextFiles'](arg1);
}

export function RevokeCliTrust(arg1) {
  return window['go']['app']['App']['RevokeCliTrust'](arg1);
}

export function RunCronJob(arg1, arg2) {
  return window['go']['app']['App']['RunCronJob'](arg1, arg2);
}

export function SaveAiConfig(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveAiConfig'](arg1, arg2, arg3, arg4);
}

export function SaveCronJob(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveCronJob'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveWebsiteConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveWebsiteConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectDownloadPath(arg1) {
  return window['go']['app']['App']['SelectDownloadPath'](arg1);
}

export function SelectMarkdownFile() {
  return window['go']['app']['App']['SelectMarkdownFile']();
}

export function SelectPrivateKey() {
  return window['go']['app']['App']['SelectPrivateKey']();
}

export function SelectTextFile() {
  return window['go']['app']['App']['SelectTextFile']();
}

export function SelectUploadFile() {
  return window['go']['app']['App']['SelectUploadFile']();
}

export function SendCommandToAll(arg1) {
  return window['go']['app']['App']['SendCommandToAll'](arg1);
}

export function SendCommandToTerminal(arg1, arg2) {
  return window['go']['app']['App']['SendCommandToTerminal'](arg1, arg2);
}

export function ServiceAction(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ServiceAction'](arg1, arg2, arg3, arg4);
}

export function ServiceLogs(arg1, arg2, arg3) {
  return window['go']['app']['App']['ServiceLogs'](arg1, arg2, arg3);
}

export function SetCronJobEnabled(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetCronJobEnabled'](arg1, arg2, arg3);
}

export function SetFirewallEnabled(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetFirewallEnabled'](arg1, arg2, arg3);
}

export function SetWebsiteEnabled(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SetWebsiteEnabled'](arg1, arg2, arg3, arg4, arg5);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['app']['App']['SkipUpdateVersion'](arg1);
}

export function StartContainer(arg1, arg2) {
  return window['go']['app']['App']['StartContainer'](arg1, arg2);
}

export function StartMonitor(arg1) {
  return window['go']['app']['App']['StartMonitor'](arg1);
}

export function StartNetworkPing(arg1, arg2) {
  return window['go']['app']['App']['StartNetworkPing'](arg1, arg2);
}

export function StartRecording(arg1, arg2) {
  return window['go']['app']['App']['StartRecording'](arg1, arg2);
}

export function StopContainer(arg1, arg2) {
  return window['go']['app']['App']['StopContainer'](arg1, arg2);
}

export function StopContainerLogs(arg1) {
  return window['go']['app']['App']['StopContainerLogs'](arg1);
}

export function StopMonitor(arg1) {
  return window['go']['app']['App']['StopMonitor'](arg1);
}

export function StopNetworkPing(arg1) {
  return window['go']['app']['App']['StopNetworkPing'](arg1);
}

export function StopRecording(arg1) {
  return window['go']['app']['App']['StopRecording'](arg1);
}

export function StopServiceLogs(arg1) {
  return window['go']['app']['App']['StopServiceLogs'](arg1);
}

export function StreamContainerLogs(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StreamContainerLogs'](arg1, arg2, arg3, arg4);
}

export function StreamServiceLogs(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StreamServiceLogs'](arg1, arg2, arg3, arg4);
}

export function TestWebsiteConfig(arg1, arg2) {
  return window['go']['app']['App']['TestWebsiteConfig'](arg1, arg2);
}

export function TraceRoute(arg1) {
  return window['go']['app']['App']['TraceRoute'](arg1);
}

export function UnregisterMarkdownContextMenu() {
  return window['go']['app']['App']['UnregisterMarkdownContextMenu']();
}

export function UnregisterTextContextMenu() {
  return window['go']['app']['App']['UnregisterTextContextMenu']();
}

export function UpdateCommand(arg1) {
  return window['go']['app']['App']['UpdateCommand'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['app']['App']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileWithPolicy(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UploadFileWithPolicy'](arg1, arg2, arg3, arg4);
}

export function WriteLocalFile(arg1, arg2) {
  return window['go']['app']['App']['WriteLocalFile'](arg1, arg2);
}

export function WriteRemoteMarkdownFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteRemoteMarkdownFile'](arg1, arg2, arg3);
}

export function WriteRemoteTextFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteRemoteTextFile'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['app']['App']['WriteToTerminal'](arg1, arg2);
}
