// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddTunnelRule(arg1:string,arg2:types.TunnelRule):Promise<types.TunnelStatus>;

export function AiChat(arg1:types.AiChatRequest):Promise<void>;

export function AiContinueChat(arg1:types.AiChatRequest):Promise<void>;

export function AiExecuteTool(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Connect(arg1:string,arg2:number,arg3:number):Promise<types.SessionInfo>;

export function ConnectWithSecrets(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<types.SessionInfo>;

export function ContainerLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function CreateCommand(arg1:types.CommandTemplate):Promise<types.CommandTemplate>;

export function CreateProfile(arg1:types.Profile):Promise<types.Profile>;

export function CreateRemoteDir(arg1:string,arg2:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<types.Profile>;

export function ExportHistory():Promise<void>;

export function GetAiConfig():Promise<types.AiConfig>;

export function GetAiUsage():Promise<types.AiTokenUsage>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetLatestMetrics(arg1:string):Promise<types.Metrics>;

export function GetNetworkPath(arg1:string):Promise<types.NetworkPath>;

export function GetProfile(arg1:string):Promise<types.Profile>;

export function GetSettings():Promise<types.AppSettings>;

export function ListAiModels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function ListCommands():Promise<Array<types.CommandTemplate>>;

export function ListContainers(arg1:string,arg2:boolean):Promise<Array<types.ContainerInfo>>;

export function ListLocalDir(arg1:string):Promise<Array<types.LocalFile>>;

export function ListLogFiles():Promise<Array<types.LogFile>>;

export function ListProfiles():Promise<Array<types.Profile>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<types.RemoteFile>>;

export function ListSessions():Promise<Array<types.SessionInfo>>;

export function ListTunnelStatus(arg1:string):Promise<Array<types.TunnelStatus>>;

export function LocalHomeDir():Promise<string>;

export function LogCommand(arg1:string,arg2:string):Promise<void>;

export function OpenDataDir():Promise<void>;

export function PingHost(arg1:string,arg2:number):Promise<types.NetworkPath>;

export function ReadLogFile(arg1:string):Promise<string>;

export function ReadLogs(arg1:number):Promise<Array<types.LogEntry>>;

export function Reconnect(arg1:string):Promise<types.SessionInfo>;

export function ReconnectWithSecrets(arg1:string,arg2:string,arg3:string):Promise<types.SessionInfo>;

export function RemoveContainer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RemoveTunnelRule(arg1:string,arg2:string):Promise<void>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetAiUsage():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string,arg2:string):Promise<void>;

export function RestartTunnels(arg1:string):Promise<Array<types.TunnelStatus>>;

export function SaveAiConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SelectDownloadPath(arg1:string):Promise<string>;

export function SelectPrivateKey():Promise<string>;

export function SelectUploadFile():Promise<string>;

export function SendCommandToAll(arg1:string):Promise<void>;

export function SendCommandToTerminal(arg1:string,arg2:string):Promise<void>;

export function StartContainer(arg1:string,arg2:string):Promise<void>;

export function StartMonitor(arg1:string):Promise<void>;

export function StartNetworkPing(arg1:string,arg2:number):Promise<void>;

export function StopContainer(arg1:string,arg2:string):Promise<void>;

export function StopContainerLogs(arg1:string,arg2:string):Promise<void>;

export function StopMonitor(arg1:string):Promise<void>;

export function StopNetworkPing(arg1:string):Promise<void>;

export function StreamContainerLogs(arg1:string,arg2:string,arg3:number):Promise<void>;

export function TraceRoute(arg1:string):Promise<types.NetworkPath>;

export function UpdateCommand(arg1:types.CommandTemplate):Promise<types.CommandTemplate>;

export function UpdateProfile(arg1:types.Profile):Promise<types.Profile>;

export function UpdateSettings(arg1:types.AppSettings):Promise<types.AppSettings>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
