// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {version} from '../models';
import {sshmanager} from '../models';

export function AddFirewallRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function AddTunnelRule(arg1:string,arg2:types.TunnelRule):Promise<types.TunnelStatus>;

export function AiChat(arg1:types.AiChatRequest):Promise<void>;

export function AiContinueChat(arg1:types.AiChatRequest):Promise<void>;

export function AiExecuteTool(arg1:string,arg2:string):Promise<string>;

export function AiExecuteTools(arg1:string,arg2:Array<string>):Promise<Record<string, string>>;

export function AnswerKeyboardInteractive(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function CancelAiChat(arg1:string,arg2:string):Promise<boolean>;

export function CancelTransfer(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<version.CheckResult>;

export function Connect(arg1:string,arg2:number,arg3:number):Promise<types.SessionInfo>;

export function ConnectLocal(arg1:number,arg2:number):Promise<types.SessionInfo>;

export function ConnectQuick(arg1:types.Profile,arg2:number,arg3:number):Promise<types.SessionInfo>;

export function ConnectWithSecrets(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<types.SessionInfo>;

export function ContainerLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function CreateCommand(arg1:types.CommandTemplate):Promise<types.CommandTemplate>;

export function CreateProfile(arg1:types.Profile):Promise<types.Profile>;

export function CreateRemoteDir(arg1:string,arg2:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteCronJob(arg1:string,arg2:string):Promise<void>;

export function DeleteFirewallRule(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRecording(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteWebsite(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<types.Profile>;

export function ExportHistory():Promise<void>;

export function ExportProfiles(arg1:boolean):Promise<string>;

export function GetAiConfig():Promise<types.AiConfig>;

export function GetAiUsage():Promise<types.AiTokenUsage>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetFirewallStatus(arg1:string):Promise<types.FirewallStatus>;

export function GetLatestMetrics(arg1:string):Promise<types.Metrics>;

export function GetNetworkPath(arg1:string):Promise<types.NetworkPath>;

export function GetProfile(arg1:string):Promise<types.Profile>;

export function GetSettings():Promise<types.AppSettings>;

export function GetStartupFile():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWebsiteConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetWebsiteStatus(arg1:string):Promise<types.WebsiteStatus>;

export function ImportOpenSSHConfig():Promise<Record<string, number>>;

export function ImportProfiles():Promise<Record<string, number>>;

export function IsMarkdownContextMenuRegistered():Promise<boolean>;

export function IsRecording(arg1:string):Promise<boolean>;

export function IsTextContextMenuRegistered():Promise<boolean>;

export function ListAiModels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function ListCommands():Promise<Array<types.CommandTemplate>>;

export function ListContainers(arg1:string,arg2:boolean):Promise<Array<types.ContainerInfo>>;

export function ListCronJobs(arg1:string):Promise<Array<types.CronJob>>;

export function ListKnownHosts():Promise<Array<sshmanager.KnownHostEntry>>;

export function ListLocalDir(arg1:string):Promise<Array<types.LocalFile>>;

export function ListLogFiles():Promise<Array<types.LogFile>>;

export function ListMarkdownFilesInDir(arg1:string):Promise<Array<string>>;

export function ListProfiles():Promise<Array<types.Profile>>;

export function ListRecordings():Promise<Array<types.Recording>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<types.RemoteFile>>;

export function ListRemoteMarkdownFilesInDir(arg1:string,arg2:string):Promise<Array<string>>;

export function ListRemoteTextFilesInDir(arg1:string,arg2:string):Promise<Array<string>>;

export function ListServices(arg1:string):Promise<Array<types.ServiceInfo>>;

export function ListSessions():Promise<Array<types.SessionInfo>>;

export function ListTextFilesInDir(arg1:string):Promise<Array<string>>;

export function ListTunnelStatus(arg1:string):Promise<Array<types.TunnelStatus>>;

export function LocalHomeDir():Promise<string>;

export function LogCommand(arg1:string,arg2:string):Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenRecentMarkdownFile(arg1:string):Promise<string>;

export function OpenRecentTextFile(arg1:string):Promise<string>;

export function OpenRecordingsDir():Promise<void>;

export function PingHost(arg1:string,arg2:number):Promise<types.NetworkPath>;

export function ReadLocalFile(arg1:string):Promise<string>;

export function ReadLocalMarkdownResourceDataURL(arg1:string,arg2:string):Promise<string>;

export function ReadLogFile(arg1:string):Promise<string>;

export function ReadLogs(arg1:number):Promise<Array<types.LogEntry>>;

export function ReadRecording(arg1:string):Promise<string>;

export function ReadRemoteMarkdownFile(arg1:string,arg2:string):Promise<string>;

export function ReadRemoteMarkdownResourceDataURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReadRemoteTextFile(arg1:string,arg2:string):Promise<string>;

export function Reconnect(arg1:string):Promise<types.SessionInfo>;

export function ReconnectWithSecrets(arg1:string,arg2:string,arg3:string):Promise<types.SessionInfo>;

export function RegisterMarkdownContextMenu():Promise<void>;

export function RegisterTextContextMenu():Promise<void>;

export function RemoveContainer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RemoveKnownHost(arg1:string,arg2:string):Promise<void>;

export function RemoveTunnelRule(arg1:string,arg2:string):Promise<void>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetAiUsage():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveLocalMarkdownLink(arg1:string,arg2:string):Promise<string>;

export function ResolveRemoteMarkdownLink(arg1:string,arg2:string):Promise<string>;

export function RestartContainer(arg1:string,arg2:string):Promise<void>;

export function RestartTunnels(arg1:string):Promise<Array<types.TunnelStatus>>;

export function RestoreTextFiles(arg1:Array<string>):Promise<Array<string>>;

export function RunCronJob(arg1:string,arg2:string):Promise<string>;

export function SaveAiConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveCronJob(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SaveWebsiteConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SelectDownloadPath(arg1:string):Promise<string>;

export function SelectMarkdownFile():Promise<string>;

export function SelectPrivateKey():Promise<string>;

export function SelectTextFile():Promise<string>;

export function SelectUploadFile():Promise<string>;

export function SendCommandToAll(arg1:string):Promise<void>;

export function SendCommandToTerminal(arg1:string,arg2:string):Promise<void>;

export function ServiceAction(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ServiceLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SetCronJobEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetFirewallEnabled(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SetWebsiteEnabled(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function StartContainer(arg1:string,arg2:string):Promise<void>;

export function StartMonitor(arg1:string):Promise<void>;

export function StartNetworkPing(arg1:string,arg2:number):Promise<void>;

export function StartRecording(arg1:string,arg2:string):Promise<string>;

export function StopContainer(arg1:string,arg2:string):Promise<void>;

export function StopContainerLogs(arg1:string):Promise<void>;

export function StopMonitor(arg1:string):Promise<void>;

export function StopNetworkPing(arg1:string):Promise<void>;

export function StopRecording(arg1:string):Promise<string>;

export function StopServiceLogs(arg1:string):Promise<void>;

export function StreamContainerLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function StreamServiceLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function TestWebsiteConfig(arg1:string,arg2:string):Promise<string>;

export function TraceRoute(arg1:string):Promise<types.NetworkPath>;

export function UnregisterMarkdownContextMenu():Promise<void>;

export function UnregisterTextContextMenu():Promise<void>;

export function UpdateCommand(arg1:types.CommandTemplate):Promise<types.CommandTemplate>;

export function UpdateProfile(arg1:types.Profile):Promise<types.Profile>;

export function UpdateSettings(arg1:types.AppSettings):Promise<types.AppSettings>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteLocalFile(arg1:string,arg2:string):Promise<void>;

export function WriteRemoteMarkdownFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteRemoteTextFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
