// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Connect(arg1:string,arg2:number,arg3:number):Promise<types.SessionInfo>;

export function ConnectWithSecrets(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<types.SessionInfo>;

export function CreateCommand(arg1:types.CommandTemplate):Promise<types.CommandTemplate>;

export function CreateProfile(arg1:types.Profile):Promise<types.Profile>;

export function CreateRemoteDir(arg1:string,arg2:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<types.Profile>;

export function ExportHistory():Promise<void>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetLatestMetrics(arg1:string):Promise<types.Metrics>;

export function GetProfile(arg1:string):Promise<types.Profile>;

export function GetSettings():Promise<types.AppSettings>;

export function ListCommands():Promise<Array<types.CommandTemplate>>;

export function ListProfiles():Promise<Array<types.Profile>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<types.RemoteFile>>;

export function ListSessions():Promise<Array<types.SessionInfo>>;

export function LogCommand(arg1:string,arg2:string):Promise<void>;

export function OpenDataDir():Promise<void>;

export function ReadLogs(arg1:number):Promise<Array<types.LogEntry>>;

export function Reconnect(arg1:string):Promise<types.SessionInfo>;

export function ReconnectWithSecrets(arg1:string,arg2:string,arg3:string):Promise<types.SessionInfo>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectDownloadPath(arg1:string):Promise<string>;

export function SelectPrivateKey():Promise<string>;

export function SelectUploadFile():Promise<string>;

export function SendCommandToTerminal(arg1:string,arg2:string):Promise<void>;

export function StartMonitor(arg1:string):Promise<void>;

export function StopMonitor(arg1:string):Promise<void>;

export function UpdateCommand(arg1:types.CommandTemplate):Promise<types.CommandTemplate>;

export function UpdateProfile(arg1:types.Profile):Promise<types.Profile>;

export function UpdateSettings(arg1:types.AppSettings):Promise<types.AppSettings>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
