// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTunnelRule(arg1, arg2) {
  return window['go']['main']['App']['AddTunnelRule'](arg1, arg2);
}

export function AiChat(arg1) {
  return window['go']['main']['App']['AiChat'](arg1);
}

export function AiContinueChat(arg1) {
  return window['go']['main']['App']['AiContinueChat'](arg1);
}

export function AiExecuteTool(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AiExecuteTool'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectWithSecrets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectWithSecrets'](arg1, arg2, arg3, arg4, arg5);
}

export function ContainerLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ContainerLogs'](arg1, arg2, arg3);
}

export function CreateCommand(arg1) {
  return window['go']['main']['App']['CreateCommand'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['CreateRemoteDir'](arg1, arg2);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFolder'](arg1, arg2, arg3);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function ExportHistory() {
  return window['go']['main']['App']['ExportHistory']();
}

export function GetAiConfig() {
  return window['go']['main']['App']['GetAiConfig']();
}

export function GetAiUsage() {
  return window['go']['main']['App']['GetAiUsage']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLatestMetrics(arg1) {
  return window['go']['main']['App']['GetLatestMetrics'](arg1);
}

export function GetNetworkPath(arg1) {
  return window['go']['main']['App']['GetNetworkPath'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListAiModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAiModels'](arg1, arg2, arg3);
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function ListContainers(arg1, arg2) {
  return window['go']['main']['App']['ListContainers'](arg1, arg2);
}

export function ListLocalDir(arg1) {
  return window['go']['main']['App']['ListLocalDir'](arg1);
}

export function ListLogFiles() {
  return window['go']['main']['App']['ListLogFiles']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteDir'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTunnelStatus(arg1) {
  return window['go']['main']['App']['ListTunnelStatus'](arg1);
}

export function LocalHomeDir() {
  return window['go']['main']['App']['LocalHomeDir']();
}

export function LogCommand(arg1, arg2) {
  return window['go']['main']['App']['LogCommand'](arg1, arg2);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function PingHost(arg1, arg2) {
  return window['go']['main']['App']['PingHost'](arg1, arg2);
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function ReadLogs(arg1) {
  return window['go']['main']['App']['ReadLogs'](arg1);
}

export function Reconnect(arg1) {
  return window['go']['main']['App']['Reconnect'](arg1);
}

export function ReconnectWithSecrets(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReconnectWithSecrets'](arg1, arg2, arg3);
}

export function RemoveContainer(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2, arg3);
}

export function RemoveTunnelRule(arg1, arg2) {
  return window['go']['main']['App']['RemoveTunnelRule'](arg1, arg2);
}

export function RenameRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemoteFile'](arg1, arg2, arg3);
}

export function ResetAiUsage() {
  return window['go']['main']['App']['ResetAiUsage']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartContainer(arg1, arg2) {
  return window['go']['main']['App']['RestartContainer'](arg1, arg2);
}

export function RestartTunnels(arg1) {
  return window['go']['main']['App']['RestartTunnels'](arg1);
}

export function SaveAiConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAiConfig'](arg1, arg2, arg3, arg4);
}

export function SelectDownloadPath(arg1) {
  return window['go']['main']['App']['SelectDownloadPath'](arg1);
}

export function SelectPrivateKey() {
  return window['go']['main']['App']['SelectPrivateKey']();
}

export function SelectUploadFile() {
  return window['go']['main']['App']['SelectUploadFile']();
}

export function SendCommandToAll(arg1) {
  return window['go']['main']['App']['SendCommandToAll'](arg1);
}

export function SendCommandToTerminal(arg1, arg2) {
  return window['go']['main']['App']['SendCommandToTerminal'](arg1, arg2);
}

export function StartContainer(arg1, arg2) {
  return window['go']['main']['App']['StartContainer'](arg1, arg2);
}

export function StartMonitor(arg1) {
  return window['go']['main']['App']['StartMonitor'](arg1);
}

export function StartNetworkPing(arg1, arg2) {
  return window['go']['main']['App']['StartNetworkPing'](arg1, arg2);
}

export function StopContainer(arg1, arg2) {
  return window['go']['main']['App']['StopContainer'](arg1, arg2);
}

export function StopContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['StopContainerLogs'](arg1, arg2);
}

export function StopMonitor(arg1) {
  return window['go']['main']['App']['StopMonitor'](arg1);
}

export function StopNetworkPing(arg1) {
  return window['go']['main']['App']['StopNetworkPing'](arg1);
}

export function StreamContainerLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['StreamContainerLogs'](arg1, arg2, arg3);
}

export function TraceRoute(arg1) {
  return window['go']['main']['App']['TraceRoute'](arg1);
}

export function UpdateCommand(arg1) {
  return window['go']['main']['App']['UpdateCommand'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
